// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetText() {
  return window['go']['main']['TextPieceTable']['GetText']();
}

export function SetText(arg1) {
  return window['go']['main']['TextPieceTable']['SetText'](arg1);
}
